### ISSUE TITLE
[Story]: Create extension hi-fi mockup

### ISSUE THREAD

**Issue by KJES4** [input-output-hk/plutus-testing-tool#16]
### Description
[Link to parent epic.](https://github.com/input-output-hk/plutus-testing-tool/issues/3)

After a proper project plan has been mapped out for the extension the next phase would be to create some high fidelity mockups of what this extension would look like and show how it would work to collect early stakeholder feedback.

### Acceptance criteria
- [x] Create designs
- [ ] Review with stakeholders
- [ ] Incorporate any necessary feedback

--
First iteration: https://www.figma.com/design/h6bznsl7cUDDIwWMA57sHl/PHA-VS-Code-Extension?node-id=5904-26871&t=5tFoYLsPqAiufLJw-0

**Comment by robpangilinanioi** [comment]
This will represent the first iteration.  We'll be discussing this more in Zurich.  So this should be ok to close.

**Comment by robpangilinanioi** [comment]
@KJES4 shared the first iteration -- https://www.figma.com/design/h6bznsl7cUDDIwWMA57sHl/PHA-VS-Code-Extension?node-id=5904-26871&t=5tFoYLsPqAiufLJw-0
