### ISSUE TITLE
Report on the IP sprint result

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/plutus-testing-tool#6]
## Description
Report on the IP sprint to better define this PI's stories

## Acceptance Criteria
 - [ ] Report on the IP sprint
 - [ ] List of suggestions to be brainstormed into stories

**Comment by amnambiar** [comment]
Added findings and summary to the document https://docs.google.com/document/d/1HXDKeZWCXdlX3C-8qF1ZKbz1SFjNAsVqQGswI9b8D-8/edit#heading=h.9i0rt546tqx7
